### ISSUE TITLE
When atomizer returns 0 atoms, build hangs

### ISSUE THREAD

**Issue by tjlee0909** [box/ClusterRunner#263]

**Comment by tjlee0909** [comment]
This might actually not be an issue, going to have to perform more testing later.

**Comment by josephharrington** [comment]
This is definitely an issue. I can reproduce locally on my mac with 
```bash
cd clusterrunner
./main.py master & ./main.py slave &
./main.py build directory --project-directory . --job-name Blah
```
where job "Blah" looks like:
```yaml
Blah:
    commands:
        - echo blahhhh
    atomizers:
        - ATOM: find . -name "something_nonexistent"
```
